# Generated by Django 4.1.2 on 2022-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('archived', models.BooleanField(default=False, verbose_name='Архив')),
            ],
            options={
                'verbose_name': 'Класс велосипедов',
                'verbose_name_plural': 'Классы велосипедов',
            },
        ),
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('archived', models.BooleanField(default=False, verbose_name='Архив')),
            ],
            options={
                'verbose_name': 'Тип велосипеда',
                'verbose_name_plural': 'Типы велосипедов',
            },
        ),
    ]
