# Generated by Django 4.1.2 on 2022-11-25 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veloride', '0002_bikeclass_biketype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64, verbose_name='Модель')),
                ('model_year', models.PositiveSmallIntegerField(verbose_name='Год модели')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новый')),
                ('old_odo', models.PositiveIntegerField(blank=True, null=True, verbose_name='С пробегом, км')),
                ('bought_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('bought_in', models.CharField(blank=True, max_length=64, null=True, verbose_name='Продавец')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('orig_price', models.FloatField(blank=True, null=True, verbose_name='Цена без скидки')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('archived', models.BooleanField(default=False, verbose_name='Архив')),
                ('bike_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bike', to='veloride.bikeclass', verbose_name='Класс')),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bike', to='veloride.biketype', verbose_name='Тип')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bike', to='veloride.organization', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
            },
        ),
    ]
