# Generated by Django 4.1.2 on 2022-11-25 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veloride', '0004_bikeeventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('route', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Маршрут')),
                ('ride_date', models.DateField(blank=True, null=True, verbose_name='Дата старта')),
                ('ride_planned', models.BooleanField(default=False, verbose_name='Запланированная поездка')),
                ('ride_was_with_me', models.BooleanField(default=False, verbose_name='Участвовал в заезде')),
                ('ride_start_dt', models.DateTimeField(verbose_name='Старт')),
                ('ride_finish_dt', models.DateTimeField(verbose_name='Финиш')),
                ('ride_time_all_h', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Общее время, ч')),
                ('ride_time_all_m', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Общее время, мин')),
                ('ride_time_all_rtm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Общее время, в минутах')),
                ('ride_time_h', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время в движении, ч')),
                ('ride_time_m', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время в движении, мин')),
                ('ride_time_rtm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время в движении, в минутах')),
                ('ride_relax', models.FloatField(blank=True, null=True, verbose_name='Доля времени без движения, %')),
                ('ride_kkal', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Энергозатраты, кКал')),
                ('ride_dst', models.FloatField(verbose_name='Дистанция')),
                ('ride_odo', models.FloatField(verbose_name='Одометр после')),
                ('ride_avg_s', models.FloatField(blank=True, null=True, verbose_name='Скорость средняя')),
                ('ride_max_s', models.FloatField(blank=True, null=True, verbose_name='Скорость макс.')),
                ('ride_avg_c', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Каденс средний')),
                ('ride_max_c', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Каденс макс.')),
                ('ride_total_asc', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Набор высоты')),
                ('ride_total_desc', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Набор спусков')),
                ('ride_avg_pwr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность средняя')),
                ('ride_max_pwr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность макс.')),
                ('ride_fun_scale', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка заезда (фан-фактор)')),
                ('ride_hard_scale', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка сложности')),
                ('ride_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на заезд')),
                ('ride_track_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на трек')),
                ('admin_mark', models.CharField(blank=True, max_length=20, null=True, verbose_name='Метка админа')),
                ('ride_bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikeride', to='veloride.bike', verbose_name='Велосипед')),
                ('ride_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikeride', to='veloride.bikeeventtype', verbose_name='Тип заезда')),
            ],
            options={
                'verbose_name': 'Велозаезд',
                'verbose_name_plural': 'Велозаезды',
            },
        ),
    ]
